# Generated by Django 4.1.2 on 2022-10-06 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.IntegerField()),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('birthday', models.DateField()),
                ('anniversary', models.DateField()),
                ('tags', models.CharField(choices=[('birth', 'Birthday'), ('anv', 'Anniversary'), ('wed', 'Wedding'), ('pty', 'Party')], max_length=20)),
                ('override_timezone', models.DateField(choices=[('EST', 'Eastern Standard Time'), ('IST', 'India Standard Time'), ('ACT', 'Australian Central Time'), ('JST', 'Japan Standard Time')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='custom_field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=20)),
                ('field_type', models.CharField(choices=[('CharField', 'Text'), ('TextField', 'Large Text'), ('DateField', 'Date'), ('IntegerField', 'Numerical')], max_length=15)),
                ('place_holder', models.CharField(max_length=50)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newfield.contact')),
            ],
        ),
        migrations.CreateModel(
            name='field_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_data', models.TextField()),
                ('custom_field_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newfield.custom_field')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newfield.contact')),
            ],
        ),
    ]
