# Generated by Django 4.1.2 on 2022-10-10 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newfield', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_field',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 10, 16, 25, 3, 76737)),
        ),
    ]
