# Generated by Django 4.1.2 on 2022-10-10 12:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newfield', '0002_alter_custom_field_add_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='agent_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='custom_field',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 10, 17, 46, 30, 193162)),
        ),
    ]
