# Generated by Django 4.1.2 on 2022-10-10 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newfield', '0003_contact_agent_id_alter_custom_field_add_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 10, 17, 50, 23, 719501)),
        ),
        migrations.AlterField(
            model_name='custom_field',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 10, 17, 50, 23, 720501)),
        ),
    ]
