# Generated by Django 4.1.2 on 2022-10-10 13:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newfield', '0004_contact_add_date_alter_custom_field_add_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 10, 18, 48, 20, 118793)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='override_timezone',
            field=models.CharField(choices=[('EST', 'Eastern Standard Time'), ('IST', 'India Standard Time'), ('ACT', 'Australian Central Time'), ('JST', 'Japan Standard Time')], max_length=5),
        ),
        migrations.AlterField(
            model_name='custom_field',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 10, 18, 48, 20, 119792)),
        ),
    ]
