# Generated by Django 4.1.2 on 2022-10-11 03:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newfield', '0005_alter_contact_add_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 11, 9, 20, 58, 598036)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_no',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='custom_field',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 11, 9, 20, 58, 599035)),
        ),
    ]
