# Generated by Django 4.1.2 on 2022-10-11 06:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newfield', '0008_alter_contact_add_date_alter_custom_field_add_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 11, 11, 31, 32, 992523)),
        ),
        migrations.AlterField(
            model_name='custom_field',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 11, 11, 31, 32, 992523)),
        ),
    ]
