# Generated by Django 4.1.2 on 2022-10-19 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newfield', '0009_alter_contact_add_date_alter_custom_field_add_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 19, 17, 15, 27, 705510)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='tags',
            field=models.CharField(choices=[('Birthday', 'Birthday'), ('Anniversary', 'Anniversary'), ('Wedding', 'Wedding'), ('Party', 'Party')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='custom_field',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 19, 17, 15, 27, 706508)),
        ),
    ]
