# Generated by Django 4.1.2 on 2022-10-21 06:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newfield', '0010_alter_contact_add_date_alter_contact_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 21, 12, 17, 16, 624790)),
        ),
        migrations.AlterField(
            model_name='custom_field',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 21, 12, 17, 16, 625789)),
        ),
        migrations.AlterField(
            model_name='field_data',
            name='contact_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='newfield.contact'),
        ),
    ]
