# Generated by Django 4.1.2 on 2022-10-21 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newfield', '0013_alter_contact_add_date_alter_custom_field_add_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 21, 16, 22, 18, 297722)),
        ),
        migrations.AlterField(
            model_name='custom_field',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 21, 16, 22, 18, 298721)),
        ),
    ]
