# Generated by Django 4.1.2 on 2022-11-01 06:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newfield', '0014_alter_contact_add_date_alter_custom_field_add_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 1, 11, 37, 39, 842268)),
        ),
        migrations.AlterField(
            model_name='custom_field',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 1, 11, 37, 39, 842268)),
        ),
    ]
